### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by dpo** [sindresorhus/dark-mode#14]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/dark-mode/issues/14)

```
$ dark-mode status
Fatal error: Unexpectedly found nil while unwrapping an Optional value
```
Subsequently, `kill -9` is unable to terminate the process.

macOS 10.14.5.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#15 Fix unwrapping nil](https://issuehunt.io/r/sindresorhus/dark-mode/pull/15)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/dark-mode/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by fenhl** [comment]
Still occurs on macOS 10.14.6. Might have something to do with the permission dialog to control system events not showing up properly depending on what app started `dark-mode`?

**Comment by ApolloZhu** [comment]
I think commit 40dbfce2d32a585a456051a5c0c043aab050834e already fixed this issue...

**Comment by fenhl** [comment]
In that case, a release or prerelease would be appreciated.

**Comment by henrikra** [comment]
Is there somebody who can make a release?

**Comment by fenhl** [comment]
Looks like [v3.0.0](https://github.com/sindresorhus/dark-mode/releases/tag/v3.0.0) has already been released and is even on [Homebrew](https://brew.sh/) already. I think this issue can be closed.

**Comment by henrikra** [comment]
Ah yeah that is true! @dpo Can you close this issue?
