### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fxcoudert** [sindresorhus/dark-mode#16]
The latest released version does not compile with Xcode 11 (because of the swift version used). Could you release a new version so we can ship it in Homebrew?

**Comment by sindresorhus** [comment]
I would prefer not doing another release as if I build with Xcode 11, the binary will only work on macOS 10.14.4 or later. Can Homebrew target the latest commit?

**Comment by fxcoudert** [comment]
> Can Homebrew target the latest commit?

No, we only ship stable released versions.

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/dark-mode/releases/tag/v3.0.0
