### ISSUE TITLE
Dark-mode breaks menu-bar

### ISSUE THREAD

**Issue by brandontravis** [sindresorhus/dark-mode#7]
When installing dark-mode via homebrew on a brand new macOS 10.12.3 installation, the menu-bar breaks.

Only the dock turns dark when activating dark-mode, and confirmed that using the system preference pane to do so (prior to install) works fine. After installing dark-mode, using the system pref UI will ONLY turn the menu-bar dark, and will no longer control the dock.

A complete uninstall does not solve this problem.

**Comment by sindresorhus** [comment]
The version of Homebrew is not updated yet: https://github.com/Homebrew/homebrew-core/pull/9665

**Comment by tareknassar** [comment]
I, too, am experiencing this problem. dark-mode 1.01 broke the menu bar and I cannot figure out how to fix it.

**Comment by sindresorhus** [comment]
The Homebrew update was merged. You can update with:

```
$ brew update && brew install -f dark-mode
```

Make sure to follow the instructions: https://github.com/sindresorhus/dark-mode/releases/tag/2.0.0
